### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Xiaoven** [Xiaoven/codegex#192]
- [x]  修改 DM_FP_NUMBER_CTOR 和 DM_NUMBER_CTOR 的 if-else关系，使它们都能被报
```java
Object[] params = new Object[]{new Integer(initialK) ,new Integer(seedFragmentLength),
				new Float(seedRmsdCutoff),
				new Integer(fragmentLength),
				new Integer(diagonalDistance), new Integer(diagonalDistance2), new Float(fragmentMiniDistance),
				new Integer(angleDiff),
				new Float(fragCompat), new Integer(maxrefine),
				new Boolean(reduceInitialFragments), new Double(joinRMSCutoff), new Boolean(joinPlo),
				new Boolean(doAngleCheck), new Boolean(doDistanceCheck), new Boolean(doRMSCheck),
				new Boolean(doDensityCheck), new Float(densityCutoff), new Float(create_co), new Integer(maxIter),
				new Float(gapOpen), new Float(gapExtension), new Integer(permutationSize), new Float(evalCutoff)};
```

- [x] DM_BOXED_PRIMITIVE_FOR_PARSING

```java
                        String[] params = key.split(":");
                        if (params == null || params.length != 2) {
                            throw new IllegalArgumentException("参数错误!");
                        }
                        int offset = Integer.valueOf(params[0]);  // 推荐使用 static int parseInt(String s) 方法，它会直接返回 int 类型，而不是返回 Integer 后又转成 int. 但只有 int i = Integer.valueOf(str)会报，int i = Integer.valueOf(int)不会，但这个转换是多余的
```
```java
long sequenceLength = Long.valueOf(m.group(2));
```

-  [ ] 自动拆包
```java
current_compound = entities.get(Integer.valueOf(value) - 1);
```

- [x] DMI_HARDCODED_ABSOLUTE_FILENAME
正则有问题，[Paths.get(String, String)](https://github.com/spotbugs/spotbugs/blob/51e586bed98393e53559a38c1f9bd15f54514efa/spotbugs/src/main/java/edu/umd/cs/findbugs/detect/BuildStringPassthruGraph.java#L106) 是 method call，不是constructor
```java
import java.nio.file.Paths;

public class DemoMmtfWriter {
	public static void main(String[] args) throws IOException, StructureException {
		MmtfActions.writeToFile(structure, Paths.get("/tmp/4cup.mmtf"));
	}
}
```

- [x] DM_NUMBER_CTOR
在第二个正则加上Character
```java
escapeChars.put(new Character('n'), new Character('\n'));

av.visit(name, new Character(
                    (char) readInt(items[readUnsignedShort(v)])));
```

- [x] NO_NOTIFY_NOT_NOTIFYALL
修改正则，使其能检查 `notify();`

- [x] spotbugs 同时报了DM_FP_NUMBER_CTOR和BX_BOXING_IMMEDIATELY_UNBOXED_TO_PERFORM_COERCION（if-else逻辑问题），和 #191 冲突了
```java
long size1= new Double(Math.min(PDPParameters.MAXSIZE,minDomSize)).longValue();
```
